apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registro-atividades
resources:
- namespace.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- api-deployment.yaml
- api-service.yaml
images:
- name: TheLeo0o/registro-atividades-backend
  newName: TheLeo0o/registro-atividades-backend
  newTag: latest
- name: leonux77/registro-atividades-backend
  newTag: be11d3296d8c66d12a082d2ded35e6323c4522a3
